const restrictedGlobals = require("confusing-browser-globals");

module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jest: true,
    node: true,
  },
  overrides: [
    {
      files: ["**/*.ts?(x)"],
      parser: "@typescript-eslint/parser",
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        ecmaVersion: 2018,
        sourceType: "module",
        warnOnUnsupportedTypeScriptVersion: true,
      },
      plugins: ["@typescript-eslint"],
      rules: {
        "@typescript-eslint/consistent-type-assertions": "warn",
        "@typescript-eslint/no-array-constructor": "warn",
        "@typescript-eslint/no-unused-expressions": [
          "error",
          {
            allowShortCircuit: true,
            allowTaggedTemplates: true,
            allowTernary: true,
          },
        ],
        "@typescript-eslint/no-unused-vars": [
          "warn",
          {
            args: "none",
            ignoreRestSiblings: true,
          },
        ],
        "@typescript-eslint/no-use-before-define": [
          "warn",
          {
            classes: false,
            functions: false,
            typedefs: false,
            variables: false,
          },
        ],
        "@typescript-eslint/no-useless-constructor": "warn",
        "default-case": "off",
        "no-array-constructor": "off",
        "no-dupe-class-members": "off",
        "no-undef": "off",
        "no-unused-expressions": "off",
        "no-unused-vars": "off",
        "no-use-before-define": "off",
        "no-useless-constructor": "off",
      },
    },
  ],
  parser: "babel-eslint",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: "module",
  },
  plugins: ["import", "jsx-a11y", "react", "react-hooks"],
  root: true,
  rules: {
    "accessor-pairs": "off",
    "array-bracket-newline": "off",
    "array-bracket-spacing": "off",
    "array-callback-return": "error",
    "array-element-newline": "off",
    "arrow-body-style": "off",
    "arrow-parens": "off",
    "arrow-spacing": "off",
    "block-scoped-var": "error",
    "block-spacing": "off",
    "brace-style": "off",
    camelcase: "warn",
    "capitalized-comments": "off",
    "class-methods-use-this": "warn",
    "comma-dangle": "off",
    "comma-spacing": "off",
    "comma-style": "off",
    complexity: "warn",
    "computed-property-spacing": "off",
    "consistent-return": "warn",
    "consistent-this": "warn",
    "constructor-super": "error",
    curly: "off",
    "default-case": [
      "warn",
      {
        commentPattern: "^no default$",
      },
    ],
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-location": ["warn", "property"],
    "dot-notation": "warn",
    "eol-last": "off",
    eqeqeq: ["warn", "smart"],
    "for-direction": "error",
    "func-call-spacing": "off",
    "func-name-matching": "error",
    "func-names": ["warn", "never"],
    "func-style": "off",
    "function-call-argument-newline": "off",
    "function-paren-newline": "off",
    "generator-star-spacing": "off",
    "getter-return": "error",
    "grouped-accessor-pairs": "warn",
    "guard-for-in": "warn",
    "id-denylist": "off",
    "id-length": "off",
    "id-match": "off",
    "implicit-arrow-linebreak": "off",
    "import/first": "error",
    "import/no-amd": "error",
    "import/no-webpack-loader-syntax": "error",
    indent: "off",
    "init-declarations": "off",
    "jsx-a11y/accessible-emoji": "warn",
    "jsx-a11y/alt-text": "warn",
    "jsx-a11y/anchor-has-content": "warn",
    "jsx-a11y/anchor-is-valid": [
      "warn",
      {
        aspects: ["noHref", "invalidHref"],
      },
    ],
    "jsx-a11y/aria-activedescendant-has-tabindex": "warn",
    "jsx-a11y/aria-props": "warn",
    "jsx-a11y/aria-proptypes": "warn",
    "jsx-a11y/aria-role": [
      "warn",
      {
        ignoreNonDOM: true,
      },
    ],
    "jsx-a11y/aria-unsupported-elements": "warn",
    "jsx-a11y/heading-has-content": "warn",
    "jsx-a11y/iframe-has-title": "warn",
    "jsx-a11y/img-redundant-alt": "warn",
    "jsx-a11y/no-access-key": "warn",
    "jsx-a11y/no-distracting-elements": "warn",
    "jsx-a11y/no-redundant-roles": "warn",
    "jsx-a11y/role-has-required-aria-props": "warn",
    "jsx-a11y/role-supports-aria-props": "warn",
    "jsx-a11y/scope": "warn",
    "jsx-quotes": "off",
    "key-spacing": "off",
    "keyword-spacing": "off",
    "line-comment-position": "off",
    "linebreak-style": "off",
    "lines-around-comment": "off",
    "lines-between-class-members": "off",
    "max-classes-per-file": "error",
    "max-depth": "warn",
    "max-len": "off",
    "max-lines": "off",
    "max-lines-per-function": ["warn", 40],
    "max-nested-callbacks": ["warn", 3],
    "max-params": ["warn", 3],
    "max-statements": "warn",
    "max-statements-per-line": "warn",
    "multiline-comment-style": "off",
    "multiline-ternary": "off",
    "new-cap": "error",
    "new-parens": "off",
    "newline-per-chained-call": "off",
    "no-alert": "warn",
    "no-array-constructor": "warn",
    "no-async-promise-executor": "error",
    "no-await-in-loop": "error",
    "no-bitwise": "error",
    "no-caller": "warn",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": ["warn", "except-parens"],
    "no-confusing-arrow": "warn",
    "no-console": "warn",
    "no-const-assign": "error",
    "no-constant-condition": "error",
    "no-constructor-return": "error",
    "no-continue": "off",
    "no-control-regex": "warn",
    "no-debugger": "error",
    "no-delete-var": "warn",
    "no-div-regex": "warn",
    "no-dupe-args": "warn",
    "no-dupe-class-members": "warn",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "warn",
    "no-duplicate-case": "warn",
    "no-duplicate-imports": "warn",
    "no-else-return": "error",
    "no-empty": "warn",
    "no-empty-character-class": "warn",
    "no-empty-function": "warn",
    "no-empty-pattern": "warn",
    "no-eq-null": "off",
    "no-eval": "error",
    "no-ex-assign": "warn",
    "no-extend-native": "warn",
    "no-extra-bind": "warn",
    "no-extra-boolean-cast": "warn",
    "no-extra-label": "warn",
    "no-extra-parens": "off",
    "no-extra-semi": "warn",
    "no-fallthrough": "warn",
    "no-floating-decimal": "warn",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-implicit-coercion": "warn",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-import-assign": "error",
    "no-inline-comments": "off",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-invalid-this": "error",
    "no-irregular-whitespace": "error",
    "no-iterator": "warn",
    "no-label-var": "error",
    "no-labels": [
      "warn",
      {
        allowLoop: true,
        allowSwitch: false,
      },
    ],
    "no-lone-blocks": "warn",
    "no-lonely-if": "warn",
    "no-loop-func": "warn",
    "no-loss-of-precision": "error",
    "no-magic-numbers": "off",
    "no-misleading-character-class": "warn",
    "no-mixed-operators": [
      "warn",
      {
        allowSamePrecedence: false,
        groups: [
          ["&", "|", "^", "~", "<<", ">>", ">>>"],
          ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
          ["&&", "||"],
          ["in", "instanceof"],
        ],
      },
    ],
    "no-mixed-spaces-and-tabs": "error",
    "no-multi-assign": "warn",
    "no-multi-spaces": "off",
    "no-multi-str": "warn",
    "no-multiple-empty-lines": "off",
    "no-native-reassign": "warn",
    "no-negated-condition": "off",
    "no-negated-in-lhs": "warn",
    "no-nested-ternary": "off",
    "no-new": "error",
    "no-new-func": "warn",
    "no-new-object": "warn",
    "no-new-symbol": "warn",
    "no-new-wrappers": "warn",
    "no-obj-calls": "warn",
    "no-octal": "warn",
    "no-octal-escape": "warn",
    "no-param-reassign": "error",
    "no-plusplus": "off",
    "no-promise-executor-return": "error",
    "no-proto": "warn",
    "no-prototype-builtins": "warn",
    "no-redeclare": ["warn"],
    "no-regex-spaces": "warn",
    "no-restricted-exports": "off",
    "no-restricted-globals": ["error"].concat(restrictedGlobals),
    "no-restricted-imports": "off",
    "no-restricted-properties": [
      "error",
      {
        message:
          "Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting",
        object: "require",
        property: "ensure",
      },
      {
        message:
          "Please use import() instead. More info: https://facebook.github.io/create-react-app/docs/code-splitting",
        object: "System",
        property: "import",
      },
    ],
    "no-restricted-syntax": ["warn", "WithStatement"],
    "no-return-assign": "warn",
    "no-return-await": "warn",
    "no-script-url": "warn",
    "no-self-assign": "warn",
    "no-self-compare": "warn",
    "no-sequences": "warn",
    "no-setter-return": "error",
    "no-shadow": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "warn",
    "no-tabs": "error",
    "no-template-curly-in-string": "warn",
    "no-ternary": "off",
    "no-this-before-super": "warn",
    "no-throw-literal": "warn",
    "no-trailing-spaces": "warn",
    "no-undef": "error",
    "no-undef-init": "off",
    "no-undefined": "off",
    "no-underscore-dangle": "off",
    "no-unexpected-multiline": "off",
    "no-unmodified-loop-condition": "off",
    "no-unneeded-ternary": "warn",
    "no-unreachable": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-expressions": [
      "error",
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
        allowTernary: true,
      },
    ],
    "no-unused-labels": "warn",
    "no-unused-vars": [
      "warn",
      {
        args: "none",
        ignoreRestSiblings: true,
      },
    ],
    "no-use-before-define": [
      "warn",
      {
        classes: false,
        functions: false,
        variables: false,
      },
    ],
    "no-useless-backreference": "warn",
    "no-useless-call": "warn",
    "no-useless-catch": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-concat": "warn",
    "no-useless-constructor": "warn",
    "no-useless-escape": "warn",
    "no-useless-rename": [
      "warn",
      {
        ignoreDestructuring: false,
        ignoreExport: false,
        ignoreImport: false,
      },
    ],
    "no-useless-return": "warn",
    "no-var": "warn",
    "no-void": "off",
    "no-warning-comments": ["warn", { terms: ["FIXME", "TODO"] }],
    "no-whitespace-before-property": "warn",
    "no-with": "error",
    "nonblock-statement-body-position": "off",
    "object-curly-newline": "off",
    "object-curly-spacing": "off",
    "object-property-newline": "off",
    "object-shorthand": ["error", "always"],
    "one-var": ["off"],
    "one-var-declaration-per-line": "off",
    "operator-assignment": ["warn", "always"],
    "operator-linebreak": "off",
    "padded-blocks": "off",
    "padding-line-between-statements": "off",
    "prefer-arrow-callback": "warn",
    "prefer-const": "warn",
    "prefer-destructuring": "warn",
    "prefer-exponentiation-operator": "warn",
    "prefer-named-capture-group": "warn",
    "prefer-numeric-literals": "warn",
    "prefer-object-spread": "warn",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "off",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "quote-props": ["warn", "as-needed"],
    quotes: "off",
    radix: "error",
    "react/forbid-foreign-prop-types": [
      "warn",
      {
        allowInPropTypes: true,
      },
    ],
    "react/jsx-no-comment-textnodes": "warn",
    "react/jsx-no-duplicate-props": "warn",
    "react/jsx-no-target-blank": "warn",
    "react/jsx-no-undef": "error",
    "react/jsx-pascal-case": [
      "warn",
      {
        allowAllCaps: true,
        ignore: [],
      },
    ],
    "react/jsx-uses-react": "warn",
    "react/jsx-uses-vars": "warn",
    "react/no-danger-with-children": "warn",
    "react/no-deprecated": "warn",
    "react/no-direct-mutation-state": "warn",
    "react/no-is-mounted": "warn",
    "react/no-typos": "error",
    "react/react-in-jsx-scope": "error",
    "react/require-render-return": "error",
    "react/style-prop-object": "warn",
    "react-hooks/exhaustive-deps": "warn",
    "react-hooks/rules-of-hooks": "error",
    "require-atomic-updates": "error",
    "require-await": "error",
    "require-unicode-regexp": "error",
    "require-yield": "warn",
    "rest-spread-spacing": ["warn", "never"],
    semi: "off",
    "semi-spacing": "off",
    "semi-style": "off",
    "sort-imports": "warn",
    "sort-keys": ["warn", "asc", { natural: true }],
    "sort-vars": "off",
    "space-before-blocks": "off",
    "space-before-function-paren": "off",
    "space-in-parens": "off",
    "space-infix-ops": "off",
    "space-unary-ops": "off",
    "spaced-comment": "off",
    strict: ["warn", "never"],
    "switch-colon-spacing": "off",
    "symbol-description": "warn",
    "template-curly-spacing": "off",
    "template-tag-spacing": "off",
    "unicode-bom": ["warn", "never"],
    "use-isnan": "warn",
    "valid-typeof": "error",
    "vars-on-top": "off",
    "wrap-iife": "error",
    "wrap-regex": "off",
    "yield-star-spacing": "off",
    yoda: ["warn", "never"],
  },
  settings: {
    react: {
      version: "detect",
    },
  },
};
