module.exports = {
  rules: {
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': 'off', // I prefer leaving the parens off when I can
    'arrow-spacing': 'warn',
    'constructor-super': 'error',
    'generator-star-spacing': ['warn', {after: true, before: false}],
    'no-class-assign': 'error',
    'no-confusing-arrow': ['error', {allowParens: true}],
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-new-symbol': 'error',
    'no-restricted-imports': 'off', // dont want to restrict imports
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-rename': 'warn',
    'no-var': 'error',
    'object-shorthand': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': ['warn', {ignoreReadBeforeAssign: true}],
    'prefer-numeric-literals': ['warn'],
    'prefer-reflect': 'warn',
    'prefer-rest-params': 'warn',
    'prefer-spread': 'warn',
    'prefer-template': 'warn',
    'require-yield': 'error',
    'rest-spread-spacing': ['warn', 'never'],
    'sort-imports': ['warn', {ignoreCase: true, memberSyntaxSortOrder: ['none', 'multiple', 'all', 'single']}], // eslint-disable-line max-len
    'symbol-description': ['warn'],
    'template-curly-spacing': 'warn',
    'yield-star-spacing': ['warn', 'after'],
  },
};
